language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
  - npm install -g hexo
  - npm install -g hexo-cli

install:
  - npm install
  
before_script:
  - git config --global user.name 'eatingmiao'
  - git config --global user.email 'eating_miao@163.com'
  - sed -i'' "s~git@github.com:eatingmiao/eatingmiao.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/eatingmiao/eatingmiao.github.io.git~" _config.yml

script:
  - hexo g

after_success:
  - hexo d
# E: Build LifeCycle

branches:
  only:
    - hexo
